name: "ğŸš€ publish"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: ğŸš€ publish
    steps:
      - name: ğŸ“š checkout
        uses: actions/checkout@v2.1.1
      - name: ğŸŸ¢ node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
        env:
          envFile: .env
      - name: ğŸ“¦ install dependencies
        run: yarn
      - name: ğŸ“ build
        run: yarn build
      - name: version bump
        run: yarn version --patch
      - name: ğŸš€ publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}